# -*- coding: utf-8 -*-
"""KNN_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJGh5QRsT4vmuE9tz1ux5p5vnviW5PYG

1.   Loading data
2.   Preprocessing
3. Splitting dataset
4. Training a model
5. Making predictions
6. Evaluating the model
"""

# Basic ML program: Classifying Iris flowers using KNN

# Step 1: Import necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Step 2: Load the dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Labels
print(X)
print(y)

# Step 3: Split into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Choose a model (K-Nearest Neighbors)
model = KNeighborsClassifier(n_neighbors=3)

# Step 5: Train the model
model.fit(X_train, y_train)

# Step 6: Make predictions
y_pred = model.predict(X_test)

# Step 7: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")